spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  profiles:
    active: dev
  messages:
    basename: r18n/messages



comment.avatar: /images/avatar.png